spring:
  application:
    name: crm
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/  # 템플릿 경로 설정
    suffix: .html                  # 파일 확장자 설정

  # maria DB setting
  datasource:
   # url: jdbc:mariadb://192.168.0.240:3306/TigerCRM?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    url: jdbc:mariadb://localhost:3306/TigerCRM?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Xkdlrj@2024!
    hikari:
      maximum-pool-size: 5

  profiles:
    active: local

# mybatis path setting
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml # mapper XML 파일 경로
  type-aliases-package: com.example.project.model # 도메인 모델 클래스가 있는 패키지 경로
  configuration:
    map-underscore-to-camel-case: true  # underscore_to_camel_case 설정


aes128:
  secret:
    key: 6c6afe32f263c477
aes:
  secret:
    key: 330ed346c97712232ba447f49b8846eb


#  config:
#    activate:
#      on-profile: "local"
#    log:
#      file-path: C:\crm\logs\server.log

#logging:
#  level:
#    #    root: warn
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

# File
#file:
#  upload:
#    path: /home/tigris/legalsystem/fileupload
#  url: http://211.47.7.48:8080/file
#  size: 100


# Cookie
cookie:
  domain: localhost
  name: _crmSystem

# Email
#mail:
#  link:
#    prev: http://211.47.7.48:8080/link/
#  subject:
#    waitingForApproval: "[법무시스템] 신규 게시물 알림"
#    requestForReview: "[법무시스템] 검토의뢰 알림"
#    underReview: "[법무시스템] 검토중 알림"
#    requestForCorrection: "[법무시스템] 수정요구 알림"
#    reject: "[법무시스템] 반려 알림"
#    reviewCompleted: "[법무시스템] 검토완료 알림"
#    reply: "[법무시스템] 댓글 알림"
#  content: |
#    법무시스템 메일 알림입니다. 아래의 [법무시스템 바로가기]를 클릭해주세요.<br/><br/><a href='{mailLink}'>[법무시스템 바로가기]</a>
#
#  activation: true
#  debug: true
#  transport:
#    protocol: smtp
#  smtp:
#    encoding: EUC-KR
#    host: smtp.gmail.com
#    port: 465
#    starttls:
#      enable: true
#    socketFactory:
#      port: 465
#      class: javax.net.ssl.SSLSocketFactory
#      fallback: false
#    auth: true
#    auth:
#      default:
#        account:
#          name: TIGRIS
#          email: tigrison.com@gmail.com
#          id: tigrison.com@gmail.com
#          pwd: trnrnzckfwisloke

# server
#server:
#  tomcat:
#    basedir: /home/tigris/legalsystem/basedir

# SSL
#server:
#  ssl:
#    key-store: classpath:key.jks
#    key-store-password: smf15666500