# server
server:
  port: 8081

spring:
  application:
    name: crm

  messages:
    basename:messages
    encoding:UTF-8

  thymeleaf:
    prefix: classpath:/templates/  # 템플릿 경로 설정
    suffix: .html                  # 파일 확장자 설정
    cache: false

  datasource:
    # url: jdbc:mariadb://localhost:3306/TigerCRM?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    # driver-class-name: org.mariadb.jdbc.Driver
    # username: root
    # password: Xkdlrj@2024!
    url: jdbc:mariadb://192.168.0.240:3306/TigerCRM?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: crmservice
    password: mp$0wnEgq*d(0CzH
    hikari:
      maximum-pool-size: 5

  servlet:
    multipart:
      max-file-size: 30MB #파일 하나의 최대 크기
      max-request-size: 30MB #한번에 최대 업로드 가능용량

  profiles:
    active: local

  mail:
    # host: smtp.sirteam.net  # SMTP 서버
    host:  smtp.naver.com  # SMTP 서버
    port: 465  # 포트
    username: dkstkdwo93@naver.com  # 발송자 이메일
    password: LXQVXWQXU631 # 발송자 이메일 비밀번호
    properties:
      mail.smtp.auth: true  # SMTP 인증
      mail.smtp.starttls.enable: false  # STARTTLS 사용
      mail.smtp.ssl.enable: true # SSL활성화

# mybatis path setting
mybatis:
  mapper-locations: classpath:/mapper/sqls/**/*.xml # mapper XML 파일 경로
  type-aliases-package: com.tiger.project.model # 도메인 모델 클래스가 있는 패키지 경로
  configuration:
    map-underscore-to-camel-case: true  # underscore_to_camel_case 설정
    cache-enabled: true        # MyBatis 캐시 사용 여부
    lazy-loading-enabled: true # Lazy Loading 사용 여부
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis SQL 로그 활성화

aes128:
  secret:
    key: 6c6afe32f263c477
aes:
  secret:
    key: 330ed346c97712232ba447f49b8846eb

# File
file:
  dir: /home/crmdevuser/files
  # dir: C:\TigerCompany\crm

# Cookie
cookie:
  domain: localhost
  name: _crmSystem