# server
server:
  port: 8081
  ssl:
    key-store: classpath:certificate.p12
    key-store-type: PKCS12
    key-store-password: 1111
  # HTTP 리다이렉트 설정
  http:
    enabled: false  # HTTP 포트를 사용하지 않도록 설정
    redirect-to-https: true # http로 접근시 https로 redirect

spring:
  profiles:
    active: dev

  messages:
    basename:messages
    encoding:UTF-8

  thymeleaf:
    prefix: classpath:/templates/  # 템플릿 경로 설정
    suffix: .html                  # 파일 확장자 설정
    cache: false

  datasource:
    url: jdbc:mariadb://61.74.221.49:30190/TigerCRM?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: crmadmin
    password: Xkdlrj@2024!
    hikari:
      maximum-pool-size: 5
  servlet:
    multipart:
      max-file-size: 30MB #파일 하나의 최대 크기
      max-request-size: 30MB #한번에 최대 업로드 가능용량
    session:
      timeout: 1800
      tracking-modes: cookie

  mail:
    host: smtp.sirteam.net  # SMTP 서버
    #host:  smtp.naver.com  # SMTP 서버
    port: 465  # 포트
    username: tiger-care@tigrison.com  # 발송자 이메일
    password: ^1s7!lRG # 발송자 이메일 비밀번호
    properties:
      mail.smtp.auth: true  # SMTP 인증
      mail.smtp.starttls.enable: false  # STARTTLS 사용
      mail.smtp.ssl.enable: true # SSL활성화
# 메일 용 url
app:
  # 개발
   base-url: https://192.168.0.240:8081
  # 로컬
  # base-url: https://localhost:8081

# mybatis path setting
mybatis:
  mapper-locations: classpath:/mapper/sqls/**/*.xml # mapper XML 파일 경로
  type-aliases-package: com.tiger.project.model # 도메인 모델 클래스가 있는 패키지 경로
  configuration:
    map-underscore-to-camel-case: true  # underscore_to_camel_case 설정
    cache-enabled: true        # MyBatis 캐시 사용 여부
    lazy-loading-enabled: true # Lazy Loading 사용 여부
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis SQL 로그 활성화

aes256:
  secret:
    key: mU6K5dhFAyOro2buJE9yKZR99D0Oh7gMnYEMFYvd6MU=

# File
file:
  dir: /home/crmdevuser/files
  logindir: /home/crmdevuser/files/Login
  #logindir: D:\tigrisCRM\src\main\resources\static\assets\images\common
  #dir: C:\Temp\fileUpload

# Cookie
cookie:
  domain: localhost
  name: _crmSystem