-- T_USER_INFO 유저 테이블
CREATE TABLE T_USER_INFO (
     USER_ID VARCHAR(50) NOT NULL COMMENT '아이디',
     USER_NAME VARCHAR(50) NOT NULL COMMENT '이름',
     USER_PW VARCHAR(200) NOT NULL COMMENT '비밀번호',
     COMPANY_ID INT NOT NULL COMMENT '고객사번호',
     USER_AUTH VARCHAR(20) NOT NULL COMMENT '사용자구분',
     JOB VARCHAR(20) COMMENT '직급',
     EMAIL VARCHAR(200) NOT NULL COMMENT '이메일주소',
     PHONE VARCHAR(20) COMMENT '핸드폰번호',
     EXTENSION_PHONE VARCHAR(20) COMMENT '회사번호',
     CREATE_DT DATETIME NOT NULL COMMENT '생성일',
     CREATE_ID VARCHAR(50) NOT NULL COMMENT '생성자',
     UPDATE_DT DATETIME COMMENT '수정일',
     UPDATE_ID VARCHAR(50) COMMENT '수정자',
     USE_YN CHAR(1) NOT NULL COMMENT '사용여부',
     PRIMARY KEY (USER_ID)  -- USER_ID를 기본 키로 설정
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- T_ALERT 알림(종모양) 테이블
CREATE TABLE T_ALERT (
     ALERT_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '알림 고유 ID',
     ALERT_TYPE VARCHAR(20) NOT NULL COMMENT '알림 종류 (예: "게시글 작성", "티켓 작성")',
     ALERT_OBJECT_ID BIGINT COMMENT '알림과 연결된 객체 ID (예: 티켓 ID, 게시글 ID)',
     CONTENT VARCHAR(200) NOT NULL COMMENT '알림 내용',
     SENDER_ID VARCHAR(20) NOT NULL COMMENT '알림 발송인',
     RECEIVER_ID VARCHAR(50) NOT NULL COMMENT '알림 수령인',
     ALERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '알림 생성 시간',
     READ_YN CHAR(1) DEFAULT 'N' COMMENT '알림 읽음 여부',

    -- 외래 키 제약 조건 추가: RECEIVER_ID가 user_info 테이블의 user_id와 연결됨
     FOREIGN KEY (RECEIVER_ID) REFERENCES T_USER_INFO(user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- T_AUTH_MANAGE 테이블
CREATE TABLE T_AUTH_MANAGE (
   AUTH_URL VARCHAR(50) NOT NULL COMMENT '접근이 허용되는 페이지 URL',
   AUTH_CODE VARCHAR(10) NOT NULL COMMENT '접근 가능한 권한 코드 (예: USER, ADMIN)',
   PRIMARY KEY (AUTH_URL, AUTH_CODE)
);